dist: bionic
language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "pypy"
  - "pypy3"

addons:
  apt:
    packages:
    - gfortran
    - flex
    - bison

jobs:
  include:
    - services: docker
    - os: osx
      language: shell
    - os: windows
      language: shell
      before_install:
        - choco install python --version 3.8.0
        - export PATH="/c/Python38:/c/Python38/Scripts:$PATH"

env:
  global:
    - TWINE_USERNAME=ntamas

install:
  - python -m pip install tox-travis twine cibuildwheel==1.1.0

script:
  - tox
  - python -m cibuildwheel --output-dir wheelhouse

notifications:
  email:
    on_success: change
    on_failure: always
