dist: bionic
language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "pypy3"

addons:
  apt:
    packages:
    - gfortran
    - flex
    - bison

install:
  - python -m pip install tox-travis

script:
  - tox

jobs:
  include:
    - stage: test
      services: docker
    - stage: wheels
      services: docker
      language: shell
      env:
        - CIBW_BEFORE_BUILD="yum install -y flex bison libxml2-devel zlib-devel"
        - CIBW_BUILD_VERBOSITY=1
      install:
        - sudo python -m pip install cibuildwheel==1.1.0
      script:
        - python -m cibuildwheel --output-dir wheelhouse
    - stage: wheels
      os: osx
      language: shell
      install:
        - python -m pip install cibuildwheel==1.1.0
      script:
        - python -m cibuildwheel --output-dir wheelhouse
    - stage: wheels
      os: windows
      language: shell
      before_install:
        - choco install python --version 3.8.0
        - export PATH="/c/Python38:/c/Python38/Scripts:$PATH"
      install:
        - python -m pip install cibuildwheel==1.1.0
      script:
        - python -m cibuildwheel --output-dir wheelhouse

notifications:
  email:
    on_success: change
    on_failure: always
