language: python

python: 2.7

env:
  - TOX_ENV=py34
  - TOX_ENV=py27

addons:
  apt:
    packages:
    - gfortran
    - flex
    - bison

install:
  - pip install tox

script:
  - tox -e $TOX_ENV

notifications:
  email:
    on_success: change
    on_failure: always

sudo: false