dist: bionic
language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "pypy3"

addons:
  apt:
    packages:
    - gfortran
    - flex
    - bison

install:
  - python -m pip install tox-travis

script:
  - tox

jobs:
  include:
    - stage: test
      services: docker
    - stage: wheels
      services: docker
      language: shell
      env:
        - CIBW_BEFORE_BUILD="yum install -y flex bison libxml2-devel zlib-devel && python setup.py build_c_core"
        - CIBW_TEST_COMMAND="cd {project} && python -m unittest"
      install:
        - sudo python -m pip install cibuildwheel==1.1.0
      script:
        - python -m cibuildwheel --output-dir wheelhouse
    - stage: wheels
      os: osx
      language: shell
      env:
        - CIBW_BEFORE_BUILD="python setup.py build_c_core"
        - CIBW_TEST_COMMAND="cd {project} && python -m unittest"
      install:
        - python -m pip install cibuildwheel==1.1.0
      script:
        - python -m cibuildwheel --output-dir wheelhouse

notifications:
  email:
    on_success: change
    on_failure: always
