dist: bionic
language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - pypy3

addons:
  apt:
    packages:
      - gfortran
      - flex
      - bison

install:
  - python -m pip install tox-travis

script:
  - tox

jobs:
  include:
    - stage: test
      services: docker
    - stage: wheels
      services: docker
      language: shell
      env:
        - CIBW_BEFORE_BUILD="yum install -y flex bison libxml2-devel zlib-devel && python setup.py build_c_core"
        - CIBW_TEST_COMMAND="cd {project} && python -m unittest"
      install:
        - sudo python -m pip install cibuildwheel==1.1.0
      script:
        - python -m cibuildwheel --output-dir wheelhouse
    - stage: wheels
      os: osx
      language: shell
      env:
        - CIBW_BEFORE_BUILD="python setup.py build_c_core"
        - CIBW_TEST_COMMAND="cd {project} && python -m unittest"
      install:
        - python -m pip install cibuildwheel==1.1.0
      script:
        - python -m cibuildwheel --output-dir wheelhouse

notifications:
  email:
    on_success: change
    on_failure: always

before_deploy:
  - git config --local user.name "ntamas"
  - git config --local user.email "ntamas@gmail.com"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG

deploy:
  provider: releases
  api_key:
    secure: CAn8qENTIZSFed7VjqcQR42mjrPGV+QptW2XkncPaRwFooizPKgRsphgKzgv7k7peEQhQs/WOEtL0a3ofYRbbucOVbJ/nTVI0qGba9Lz/afsQ2UsbGnan0hXua9D/bo1wRhgqz8j0q6LHb3O8rgQOAKi8hWCChglr2saeRsy5Fc=
  file: wheelhouse/*.whl
  file_glob: true
  draft: true
  skip_cleanup: true
  on:
    repo: igraph/python-igraph
