image:
  - Visual Studio 2017

environment:
  PATH: C:\msys64\usr\bin;C:\msys64\mingw64\bin;C:\Windows\System32;C:\Windows;%PATH%
  MSYSTEM: MINGW64
  TARGET_ARCH: "x64"
  CIBW_BEFORE_BUILD: python setup.py build_c_core
  CIBW_SKIP: "*-win32"
  IGRAPH_EXTRA_CONFIGURE_ARGS: "--disable-graphml"
  # DEVENV_EXECUTABLE: C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\devenv.exe

platform:
  - x64

install:
  - bash -lc "pacman --needed --noconfirm -Sy pacman-mirrors"
  - bash -lc "pacman --noconfirm -Sy"
  - bash -lc "pacman --noconfirm -S autoconf automake bison flex libtool mingw-w64-x86_64-libtool"
  - bash -lc "pacman --noconfirm -S libxml2-devel zip"
  - pip install cibuildwheel==1.1.0

before_build:
  - git submodule update --init --recursive

build_script:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - cibuildwheel --output-dir wheelhouse

artifacts:
  - path: "wheelhouse\\*.whl"
    name: Wheels

