name: igraph &ndash; the network analysis package
destination: jekyll_output
future: true
include: [ _static, _images ]
exclude: [ source, Gemfile, Gemfile.lock, build_old_sources.py ]
keep_files: [ ]
markdown: kramdown
kramdown:
  input: GFM
url: "https://igraph.org/python"
plugins:
  - jekyll-sitemap
defaults:
  -
    scope:
      path: ""
    values:
      layout: "post"
